# Generated by Django 4.2.7 on 2024-07-04 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("sign_date", models.DateField()),
                ("first_date", models.DateField()),
                ("last_date", models.DateField()),
                ("total", models.IntegerField()),
                ("discount", models.IntegerField()),
                ("monthly", models.IntegerField()),
                ("join_fee", models.IntegerField()),
                ("location", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("Last_Name", models.CharField(max_length=40)),
                ("First_Name", models.CharField(max_length=30)),
                ("Patronim", models.CharField(max_length=40, null=True)),
                ("Phone", models.CharField(max_length=20)),
                ("IIN", models.CharField(max_length=12)),
                ("ID_number", models.CharField(max_length=9)),
                ("ID_date", models.DateField()),
                ("ID_org", models.CharField(max_length=30)),
                ("Working_Place", models.CharField(max_length=30, null=True)),
                ("Position", models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("Last_Name", models.CharField(max_length=40)),
                ("First_Name", models.CharField(max_length=30)),
                ("Patronim", models.CharField(max_length=40, null=True)),
                ("birthdate", models.DateField()),
                ("IIN", models.CharField(max_length=12)),
                ("grade", models.IntegerField()),
                ("letter", models.CharField(max_length=1, null=True)),
                ("nationality", models.CharField(max_length=20, null=True)),
                ("prev_school", models.CharField(max_length=10, null=True)),
                ("phone", models.CharField(max_length=20, null=True)),
                (
                    "contract",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_manager.contract",
                    ),
                ),
                (
                    "parent_1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mom",
                        to="user_manager.parent",
                    ),
                ),
                (
                    "parent_2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dad",
                        to="user_manager.parent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="List_Of_Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Last_Name", models.CharField(max_length=40)),
                ("First_Name", models.CharField(max_length=30)),
                ("Class", models.CharField(max_length=30)),
                ("Phone", models.CharField(max_length=20)),
                ("Payment", models.IntegerField()),
                ("Sep", models.IntegerField(default=0)),
                ("Oct", models.IntegerField(default=0)),
                ("Nov", models.IntegerField(default=0)),
                ("Dec", models.IntegerField(default=0)),
                ("Jan", models.IntegerField(default=0)),
                ("Mar", models.IntegerField(default=0)),
                ("Apr", models.IntegerField(default=0)),
                ("May", models.IntegerField(default=0)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_manager.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Curator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "curator_class1",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "curator_class2",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "curator_class3",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("picture", models.CharField(max_length=150, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
