# Generated by Django 4.2.7 on 2024-08-26 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0002_student_comment"),
    ]

    operations = [
        migrations.RenameField(model_name="contract", old_name="id", new_name="numb",),
        migrations.RemoveField(model_name="contract", name="sign_date",),
        migrations.RemoveField(model_name="parent", name="IIN",),
    ]
