# Generated by Django 4.2.7 on 2024-09-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0005_parent_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[("Под", "Подписан"), ("НеПод", "Не подписан")],
                default="НеПод",
                max_length=50,
            ),
        ),
    ]
