# Generated by Django 4.2.7 on 2024-09-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0008_remove_student_parent_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="prev_school",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
