# Generated by Django 4.1.6 on 2024-09-13 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_manager", "0009_alter_student_prev_school"),
    ]

    operations = [
        migrations.CreateModel(
            name="LMS_User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("surname", models.CharField(max_length=150)),
                ("picture", models.CharField(default="Avatar.png", max_length=150)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("Админ", "Администрация"),
                            ("Бух", "Бухгалтер"),
                            ("ВнСв", "Зам по ВСиРШ"),
                            ("Дело", "Делопроизводитель"),
                            ("Дир", "Директор"),
                            ("Кур", "Куратор"),
                        ],
                        default="Админ",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="curator", name="user",),
        migrations.RenameField(
            model_name="contract", old_name="location", new_name="template_location",
        ),
        migrations.AddField(
            model_name="contract",
            name="join_fee_status",
            field=models.CharField(
                choices=[("Не Оплачено", "Не Оплачено"), ("Оплачено", "Оплачено")],
                default="Не Оплачено",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="signed_location",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.DeleteModel(name="Admin",),
        migrations.DeleteModel(name="Curator",),
    ]
