# Generated by Django 4.1.6 on 2024-09-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0010_lms_user_remove_curator_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="lms_user", name="surname",),
        migrations.AddField(
            model_name="lms_user",
            name="email",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="lms_user",
            name="phone",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
