# Generated by Django 4.1.6 on 2024-09-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0011_remove_lms_user_surname_lms_user_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lms_user",
            name="phone",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
