# Generated by Django 4.1.6 on 2024-09-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0012_alter_lms_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[("Лид", "В работе"), ("Акт", "Активный"), ("Выб", "Выбыл")],
                default="Лид",
                max_length=30,
            ),
        ),
    ]
